version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_tasksurvey
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password123!
      TZ: "Asia/Jakarta"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  app:
    build: .
    container_name: blazor_tasksurvey
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=tasksurvey_db;User Id=sa;Password=Password123!;TrustServerCertificate=True;"
      TZ: "Asia/Jakarta"
    depends_on:
      - db

volumes:
  sql_data:
